default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - release
  - publish

semantic_release:
  stage: release
  script:
    - npm run build
    - npm run semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

publish_to_npm:
  stage: publish
  script:
    - |
      if git diff --name-only HEAD~1 HEAD | grep -q "^package.json$"; then
        echo "package.json changed, publishing to npm..."
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        npm publish
      else
        echo "package.json did not change, skipping npm publish."
      fi
  rules:
    - when: manual
      allow_failure: false
  dependencies:
    - semantic_release
  environment:
    name: production
